### PR TITLE
Updated to support Laravel 5.7

### PR DESCRIPTION
**Pull request by trideout**

### CODE REVIEW

**Comment by ellisio** [comment]
@GrahamCampbell Can we get this merged please? It's preventing our upgrade to Laravel 5.7.

Edit: Actually, @trideout, looks like this needs changes to the `travis.yml` as well to add a 5.7 test suite.

**Comment by ChrisThompsonTLDR** [comment]
Missing update in the readme.

**Comment by jonbnewman** [comment]
There are currently 3 pull requests all trying to fix the laravel version requirement. This issue is preventing us from updating our environment...can we get some traction on **one of these** and have a merge please?

@GrahamCampbell @jbrooksuk @joecohens 

This is the oldest one, sitting at nearly 3 weeks old as of this time. The others are:

* https://github.com/AltThree/Segment/pull/16
* https://github.com/AltThree/Segment/pull/17

**Comment by ellisio** [comment]
image

I sent @GrahamCampbell an email, but never heard back. I have Laravel 5.7 in my queue this sprint for work, and need this merged.

If there is not a merge by Monday, I'll fork the repo and publish it to Packagist for everyone to use in the mean time.

**Comment by GrahamCampbell** [comment]
Laravel 5.7 support will appear in the next release, today.

**Pull request closed without merging**
