### PR TITLE
Adding support for Laravel 5.8.

### PR DESCRIPTION
**Pull request by ChrisThompsonTLDR**

### CODE REVIEW

**Comment by ChrisThompsonTLDR** [comment]
@GrahamCampbell can we get an update on this pull request?

**Comment by ziming** [comment]
Look forward to this getting merged too!

**Comment by ChrisThompsonTLDR** [comment]
@GrahamCampbell hello?

**Comment by GrahamCampbell** [comment]
Thanks for the PR. Support for 5.8 will be landing soon. :)

**Comment by ChrisThompsonTLDR** [comment]
Why was this closed instead of accepted?

We've been using our fork in production for weeks.

**Comment by GrahamCampbell** [comment]
> Why was this closed instead of accepted?

Because it doesn't update travis to test on the newer version.

**Pull request closed without merging**
